// src/svelte/typing/Typing.svelte
<script lang="ts">
import { onMount, onDestroy } from 'svelte';
import { Typing } from '../../core/typing/index.js';
import type { TypingOptions } from '../../core/typing/index.js';

export interface TypingRef {
  start: () => void;
  stop: () => void;
  reset: () => void;
  setText: (text: string) => void;
  destroy: () => void;
}

interface Props {
  text: string;
  speed?: number;
  delay?: number;
  enabled?: boolean;
  threshold?: number;
  rootMargin?: string;
  triggerOnce?: boolean;
  showCursor?: boolean;
  cursorChar?: string;
  className?: string;
  style?: string;
  onUpdate?: (text: string) => void;
  onComplete?: () => void;
}

let {
  text,
  speed = 50,
  delay = 0,
  enabled = true,
  threshold = 0.2,
  rootMargin = '0px 0px -100px 0px',
  triggerOnce = false,
  showCursor = true,
  cursorChar = '|',
  className = '',
  style = '',
  onUpdate,
  onComplete,
}: Props = $props();

let containerRef: HTMLDivElement | null = null;
let instanceRef: Typing | null = null;

onMount(() => {
  if (!containerRef) return;

  const options: TypingOptions = {
    text,
    speed,
    delay,
    enabled,
    threshold,
    rootMargin,
    triggerOnce,
    showCursor,
    cursorChar,
    onUpdate,
    onComplete,
  };

  instanceRef = new Typing(containerRef, options);
});

onDestroy(() => {
  if (instanceRef) {
    instanceRef.destroy();
    instanceRef = null;
  }
});

// text 변경 감지
$effect(() => {
  if (instanceRef && text !== instanceRef['originalText']) {
    instanceRef.setText(text);
  }
});

// ref를 통해 메서드 노출
export function start() {
  instanceRef?.start();
}

export function stop() {
  instanceRef?.stop();
}

export function reset() {
  instanceRef?.reset();
}

export function setText(newText: string) {
  instanceRef?.setText(newText);
}

export function destroy() {
  if (instanceRef) {
    instanceRef.destroy();
    instanceRef = null;
  }
}
</script>

<div bind:this={containerRef} class={className} style={style}></div>

// src/vue/typing/Typing.vue
<template>
  <div ref="containerRef" :class="className" :style="style"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { Typing } from '../../core/typing/index.js';
import type { TypingOptions } from '../../core/typing/index.js';

export interface TypingRef {
  start: () => void;
  stop: () => void;
  reset: () => void;
  setText: (text: string) => void;
  destroy: () => void;
}

interface Props extends Omit<TypingOptions, 'onUpdate' | 'onComplete'> {
  className?: string;
  style?: string | Record<string, string>;
  onUpdate?: (text: string) => void;
  onComplete?: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  speed: 50,
  delay: 0,
  enabled: true,
  threshold: 0.2,
  rootMargin: '0px 0px -100px 0px',
  triggerOnce: false,
  showCursor: true,
  cursorChar: '|',
});

const containerRef = ref<HTMLElement | null>(null);
const instanceRef = ref<Typing | null>(null);

onMounted(() => {
  if (!containerRef.value) return;

  const options: TypingOptions = {
    text: props.text,
    speed: props.speed,
    delay: props.delay,
    enabled: props.enabled,
    threshold: props.threshold,
    rootMargin: props.rootMargin,
    triggerOnce: props.triggerOnce,
    showCursor: props.showCursor,
    cursorChar: props.cursorChar,
    onUpdate: props.onUpdate,
    onComplete: props.onComplete,
  };

  instanceRef.value = new Typing(containerRef.value, options);
});

onUnmounted(() => {
  if (instanceRef.value) {
    instanceRef.value.destroy();
    instanceRef.value = null;
  }
});

// text 변경 감지
watch(() => props.text, (newText) => {
  if (instanceRef.value && newText !== instanceRef.value['originalText']) {
    instanceRef.value.setText(newText);
  }
});

// ref를 통해 메서드 노출
defineExpose({
  start: () => instanceRef.value?.start(),
  stop: () => instanceRef.value?.stop(),
  reset: () => instanceRef.value?.reset(),
  setText: (text: string) => instanceRef.value?.setText(text),
  destroy: () => {
    if (instanceRef.value) {
      instanceRef.value.destroy();
      instanceRef.value = null;
    }
  },
});
</script>
