// src/react/slide/Slide.tsx
import React, { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import { Slide } from '../../core/slide/index.js';
import type { SlideOptions } from '../../core/slide/index.js';

export interface SlideRef {
  start: () => void;
  stop: () => void;
  reset: () => void;
  updateConfig: (config: Partial<SlideOptions>) => void;
  destroy: () => void;
}

interface SlideProps extends Omit<SlideOptions, 'onStart' | 'onComplete'> {
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
  onStart?: () => void;
  onComplete?: () => void;
}

const SlideComponent = forwardRef<SlideRef, SlideProps>(
  (props, ref) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const instanceRef = useRef<Slide | null>(null);

    useEffect(() => {
      if (!containerRef.current) return;

      // 이미 인스턴스가 있으면 생성하지 않음 (React Strict Mode 대응)
      if (instanceRef.current) {
        return;
      }

      const {
        className,
        style,
        children,
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart,
        onComplete,
      } = props;

      const options: SlideOptions = {
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart,
        onComplete,
      };

      instanceRef.current = new Slide(containerRef.current, options);

      return () => {
        if (instanceRef.current) {
          instanceRef.current.destroy();
          instanceRef.current = null;
        }
      };
    }, []);

    // props 변경 시 설정 업데이트
    useEffect(() => {
      if (!instanceRef.current) return;

      const {
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart,
        onComplete,
      } = props;

      instanceRef.current.updateConfig({
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart,
        onComplete,
      });
    }, [
      props.direction,
      props.distance,
      props.duration,
      props.easing,
      props.threshold,
      props.rootMargin,
      props.triggerOnce,
      props.enabled,
      props.onStart,
      props.onComplete,
    ]);

    useImperativeHandle(ref, () => ({
      start: () => {
        if (!instanceRef.current) {
          console.warn('Slide: 인스턴스가 아직 초기화되지 않았습니다.');
          return;
        }
        instanceRef.current.start();
      },
      stop: () => {
        if (!instanceRef.current) {
          console.warn('Slide: 인스턴스가 아직 초기화되지 않았습니다.');
          return;
        }
        instanceRef.current.stop();
      },
      reset: () => {
        if (!instanceRef.current) {
          console.warn('Slide: 인스턴스가 아직 초기화되지 않았습니다.');
          return;
        }
        instanceRef.current.reset();
      },
      updateConfig: (config: Partial<SlideOptions>) => {
        if (!instanceRef.current) {
          console.warn('Slide: 인스턴스가 아직 초기화되지 않았습니다.');
          return;
        }
        instanceRef.current.updateConfig(config);
      },
      destroy: () => {
        if (instanceRef.current) {
          instanceRef.current.destroy();
          instanceRef.current = null;
        }
      },
    }));

    return (
      <div
        ref={containerRef}
        className={props.className}
        style={props.style}
      >
        {props.children}
      </div>
    );
  }
);

SlideComponent.displayName = 'Slide';

export default SlideComponent;

// src/svelte/slide/Slide.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import { Slide } from '../../core/slide/index';
  import type { SlideOptions } from '../../core/slide/index';

  export let direction: 'top' | 'right' | 'bottom' | 'left' = 'bottom';
  export let distance: string = '50px';
  export let duration: number = 800;
  export let easing: (t: number) => number = (t) => t;
  export let threshold: number = 0.1;
  export let rootMargin: string = '0px';
  export let triggerOnce: boolean = false;
  export let enabled: boolean = true;
  export let className: string = '';
  export let style: Record<string, any> = {};

  const dispatch = createEventDispatcher<{
    start: void;
    complete: void;
  }>();

  let container: HTMLDivElement;
  let instance: Slide | null = null;

  $: {
    if (instance) {
      instance.updateConfig({
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart: () => {
          dispatch('start');
        },
        onComplete: () => {
          dispatch('complete');
        },
      });
    }
  }

  onMount(() => {
    if (!container) return;

    const options: SlideOptions = {
      direction,
      distance,
      duration,
      easing,
      threshold,
      rootMargin,
      triggerOnce,
      enabled,
      onStart: () => {
        dispatch('start');
      },
      onComplete: () => {
        dispatch('complete');
      },
    };

    instance = new Slide(container, options);
  });

  onDestroy(() => {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  });

  export function start() {
    if (instance) {
      instance.start();
    }
  }

  export function stop() {
    if (instance) {
      instance.stop();
    }
  }

  export function reset() {
    if (instance) {
      instance.reset();
    }
  }

  export function updateConfig(config: Partial<SlideOptions>) {
    if (instance) {
      instance.updateConfig(config);
    }
  }

  export function destroy() {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  }
</script>

<div bind:this={container} class={className} style={style}>
  <slot />
</div>
