// src/svelte/slide/Slide.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import { Slide } from '../../core/slide/index';
  import type { SlideOptions } from '../../core/slide/index';

  export let direction: 'top' | 'right' | 'bottom' | 'left' = 'bottom';
  export let distance: string = '50px';
  export let duration: number = 800;
  export let easing: (t: number) => number = (t) => t;
  export let threshold: number = 0.1;
  export let rootMargin: string = '0px';
  export let triggerOnce: boolean = false;
  export let enabled: boolean = true;
  export let className: string = '';
  export let style: Record<string, any> = {};

  const dispatch = createEventDispatcher<{
    start: void;
    complete: void;
  }>();

  let container: HTMLDivElement;
  let instance: Slide | null = null;

  $: {
    if (instance) {
      instance.updateConfig({
        direction,
        distance,
        duration,
        easing,
        threshold,
        rootMargin,
        triggerOnce,
        enabled,
        onStart: () => {
          dispatch('start');
        },
        onComplete: () => {
          dispatch('complete');
        },
      });
    }
  }

  onMount(() => {
    if (!container) return;

    const options: SlideOptions = {
      direction,
      distance,
      duration,
      easing,
      threshold,
      rootMargin,
      triggerOnce,
      enabled,
      onStart: () => {
        dispatch('start');
      },
      onComplete: () => {
        dispatch('complete');
      },
    };

    instance = new Slide(container, options);
  });

  onDestroy(() => {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  });

  export function start() {
    if (instance) {
      instance.start();
    }
  }

  export function stop() {
    if (instance) {
      instance.stop();
    }
  }

  export function reset() {
    if (instance) {
      instance.reset();
    }
  }

  export function updateConfig(config: Partial<SlideOptions>) {
    if (instance) {
      instance.updateConfig(config);
    }
  }

  export function destroy() {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  }
</script>

<div bind:this={container} class={className} style={style}>
  <slot />
</div>

// src/vue/slide/Slide.vue
<template>
  <div ref="container" :class="className" :style="style">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { Slide } from '../../core/slide/index';
import type { SlideOptions } from '../../core/slide/index';

interface Props extends Partial<SlideOptions> {
  className?: string;
  style?: Record<string, any>;
}

const props = withDefaults(defineProps<Props>(), {
  direction: 'bottom',
  distance: '50px',
  duration: 800,
  easing: () => (t: number) => t,
  threshold: 0.1,
  rootMargin: '0px',
  triggerOnce: false,
  enabled: true,
  className: '',
  style: () => ({}),
  onStart: null,
  onComplete: null,
});

const emit = defineEmits<{
  start: [];
  complete: [];
}>();

const container = ref<HTMLElement | null>(null);
let instance: Slide | null = null;

const init = () => {
  if (!container.value) return;

  const options: SlideOptions = {
    direction: props.direction,
    distance: props.distance,
    duration: props.duration,
    easing: props.easing,
    threshold: props.threshold,
    rootMargin: props.rootMargin,
    triggerOnce: props.triggerOnce,
    enabled: props.enabled,
    onStart: () => {
      if (props.onStart) props.onStart();
      emit('start');
    },
    onComplete: () => {
      if (props.onComplete) props.onComplete();
      emit('complete');
    },
  };

  instance = new Slide(container.value, options);
};

// props 변경 감지
watch(
  () => [
    props.direction,
    props.distance,
    props.duration,
    props.easing,
    props.threshold,
    props.rootMargin,
    props.triggerOnce,
    props.enabled,
  ],
  () => {
    if (instance) {
      instance.updateConfig({
        direction: props.direction,
        distance: props.distance,
        duration: props.duration,
        easing: props.easing,
        threshold: props.threshold,
        rootMargin: props.rootMargin,
        triggerOnce: props.triggerOnce,
        enabled: props.enabled,
        onStart: () => {
          if (props.onStart) props.onStart();
          emit('start');
        },
        onComplete: () => {
          if (props.onComplete) props.onComplete();
          emit('complete');
        },
      });
    }
  }
);

onMounted(() => {
  init();
});

onBeforeUnmount(() => {
  if (instance) {
    instance.destroy();
    instance = null;
  }
});

// 외부에서 사용할 수 있는 메서드 노출
defineExpose({
  start: () => {
    if (instance) instance.start();
  },
  stop: () => {
    if (instance) instance.stop();
  },
  reset: () => {
    if (instance) instance.reset();
  },
  updateConfig: (config: Partial<SlideOptions>) => {
    if (instance) instance.updateConfig(config);
  },
  destroy: () => {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  },
});
</script>
