// examples/react-example.jsx
import React, { useRef } from 'react';
import MasonEffect from 'masoneffect/react';

function App() {
  const effectRef = useRef(null);

  const handleMorph = () => {
    effectRef.current?.morph();
  };

  const handleScatter = () => {
    effectRef.current?.scatter();
  };

  const handleChangeText = () => {
    const texts = ['Hello', 'World', 'Mason', 'Effect'];
    const randomText = texts[Math.floor(Math.random() * texts.length)];
    effectRef.current?.morph(randomText);
  };

  return (
    <div style={{ width: '100%', height: '70vh', background: '#000' }}>
      <MasonEffect
        ref={effectRef}
        text="Hello React"
        particleColor="#00ff88"
        maxParticles={2000}
        onReady={(instance) => {
          console.log('Ready!', instance);
        }}
      />
      <div style={{ padding: '20px', display: 'flex', gap: '10px' }}>
        <button onClick={handleMorph}>Morph</button>
        <button onClick={handleScatter}>Scatter</button>
        <button onClick={handleChangeText}>텍스트 변경</button>
      </div>
    </div>
  );
}

export default App;

// examples/vue-example.vue
<template>
  <div style="width: 100%; height: 70vh; background: #000">
    <MasonEffect
      ref="effectRef"
      text="Hello Vue"
      :particle-color="'#00ff88'"
      :max-particles="2000"
      @ready="onReady"
    />
    <div style="padding: 20px; display: flex; gap: 10px">
      <button @click="handleMorph">Morph</button>
      <button @click="handleScatter">Scatter</button>
      <button @click="handleChangeText">텍스트 변경</button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import MasonEffect from 'masoneffect/vue';

const effectRef = ref(null);

const handleMorph = () => {
  effectRef.value?.morph();
};

const handleScatter = () => {
  effectRef.value?.scatter();
};

const handleChangeText = () => {
  const texts = ['Hello', 'World', 'Mason', 'Effect'];
  const randomText = texts[Math.floor(Math.random() * texts.length)];
  effectRef.value?.morph(randomText);
};

const onReady = (instance) => {
  console.log('Ready!', instance);
};
</script>
