// src/vue/textSpin/TextSpin.vue
<template>
  <div ref="container" :class="className" :style="style"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { TextSpin } from '../../core/textSpin/index';
import type { TextSpinOptions } from '../../core/textSpin/index';

interface Props extends Omit<TextSpinOptions, 'onStart' | 'onComplete'> {
  className?: string;
  style?: Record<string, any>;
  onStart?: () => void;
  onComplete?: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  text: '',
  delay: 0.2,
  duration: 0.6,
  randomDelay: 2,
  threshold: 0.1,
  rootMargin: '0px',
  root: null,
  triggerOnce: false,
  enabled: true,
  className: '',
  style: () => ({}),
  onStart: null,
  onComplete: null,
});

const emit = defineEmits<{
  start: [];
  complete: [];
}>();

const container = ref<HTMLElement | null>(null);
let instance: TextSpin | null = null;

const init = () => {
  if (!container.value) return;

  const options: TextSpinOptions = {
    text: props.text,
    delay: props.delay,
    duration: props.duration,
    randomDelay: props.randomDelay,
    threshold: props.threshold,
    rootMargin: props.rootMargin,
    root: props.root,
    triggerOnce: props.triggerOnce,
    enabled: props.enabled,
    onStart: () => {
      if (props.onStart) props.onStart();
      emit('start');
    },
    onComplete: () => {
      if (props.onComplete) props.onComplete();
      emit('complete');
    },
  };

  instance = new TextSpin(container.value, options);
};

onMounted(() => {
  init();
});

onBeforeUnmount(() => {
  if (instance) {
    instance.destroy();
    instance = null;
  }
});

// props 변경 감지
watch(
  () => [
    props.text,
    props.delay,
    props.duration,
    props.randomDelay,
    props.threshold,
    props.rootMargin,
    props.root,
    props.triggerOnce,
    props.enabled,
    props.onStart,
    props.onComplete,
  ],
  () => {
    if (instance) {
      instance.updateConfig({
        text: props.text,
        delay: props.delay,
        duration: props.duration,
        randomDelay: props.randomDelay,
        threshold: props.threshold,
        rootMargin: props.rootMargin,
        root: props.root,
        triggerOnce: props.triggerOnce,
        enabled: props.enabled,
        onStart: props.onStart || undefined,
        onComplete: props.onComplete || undefined,
      });
    }
  },
  { deep: true }
);

// 외부에서 사용할 수 있는 메서드 노출
defineExpose({
  start: () => {
    if (instance) instance.start();
  },
  stop: () => {
    if (instance) instance.stop();
  },
  reset: () => {
    if (instance) instance.reset();
  },
  updateText: (text: string) => {
    if (instance) instance.updateText(text);
  },
  updateConfig: (config: Partial<TextSpinOptions>) => {
    if (instance) instance.updateConfig(config);
  },
  destroy: () => {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  },
});
</script>

// src/svelte/textSpin/TextSpin.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { TextSpin } from '../../core/textSpin/index';
  import type { TextSpinOptions } from '../../core/textSpin/index';

  export let text: string = '';
  export let delay: number = 0.2;
  export let duration: number = 0.6;
  export let randomDelay: number = 2;
  export let threshold: number = 0.1;
  export let rootMargin: string = '0px';
  export let root: HTMLElement | null = null;
  export let triggerOnce: boolean = false;
  export let enabled: boolean = true;
  export let className: string = '';
  export let style: Record<string, any> = {};
  export let onStart: (() => void) | null = null;
  export let onComplete: (() => void) | null = null;

  let container: HTMLDivElement;
  let instance: TextSpin | null = null;

  // Props 변경 감지 (Reactive statement)
  $: {
    if (instance) {
      instance.updateConfig({
        text,
        delay,
        duration,
        randomDelay,
        threshold,
        rootMargin,
        root,
        triggerOnce,
        enabled,
        onStart: onStart || undefined,
        onComplete: onComplete || undefined,
      });
    }
  }

  onMount(() => {
    if (!container) return;

    const options: TextSpinOptions = {
      text,
      delay,
      duration,
      randomDelay,
      threshold,
      rootMargin,
      root,
      triggerOnce,
      enabled,
      onStart: onStart || undefined,
      onComplete: onComplete || undefined,
    };

    instance = new TextSpin(container, options);
  });

  onDestroy(() => {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  });

  // 외부에서 사용할 수 있는 메서드 노출
  export function start() {
    if (instance) instance.start();
  }

  export function stop() {
    if (instance) instance.stop();
  }

  export function reset() {
    if (instance) instance.reset();
  }

  export function updateText(newText: string) {
    if (instance) instance.updateText(newText);
  }

  export function updateConfig(config: Partial<TextSpinOptions>) {
    if (instance) instance.updateConfig(config);
  }

  export function destroy() {
    if (instance) {
      instance.destroy();
      instance = null;
    }
  }
</script>

<div bind:this={container} class={className} style={style}></div>
