// src/svelte/typing/Typing.svelte
<script lang="ts">
import { onMount, onDestroy } from 'svelte';
import { Typing } from '../../core/typing/index.js';
import type { TypingOptions } from '../../core/typing/index.js';

export interface TypingRef {
  start: () => void;
  stop: () => void;
  reset: () => void;
  setText: (text: string) => void;
  destroy: () => void;
}

interface Props {
  text: string;
  speed?: number;
  delay?: number;
  enabled?: boolean;
  threshold?: number;
  rootMargin?: string;
  triggerOnce?: boolean;
  showCursor?: boolean;
  cursorChar?: string;
  className?: string;
  style?: string;
  onUpdate?: (text: string) => void;
  onComplete?: () => void;
}

let {
  text,
  speed = 50,
  delay = 0,
  enabled = true,
  threshold = 0.2,
  rootMargin = '0px 0px -100px 0px',
  triggerOnce = false,
  showCursor = true,
  cursorChar = '|',
  className = '',
  style = '',
  onUpdate,
  onComplete,
}: Props = $props();

let containerRef: HTMLDivElement | null = null;
let instanceRef: Typing | null = null;

onMount(() => {
  if (!containerRef) return;

  const options: TypingOptions = {
    text,
    speed,
    delay,
    enabled,
    threshold,
    rootMargin,
    triggerOnce,
    showCursor,
    cursorChar,
    onUpdate,
    onComplete,
  };

  instanceRef = new Typing(containerRef, options);
});

onDestroy(() => {
  if (instanceRef) {
    instanceRef.destroy();
    instanceRef = null;
  }
});

// text 변경 감지
$effect(() => {
  if (instanceRef && text !== instanceRef['originalText']) {
    instanceRef.setText(text);
  }
});

// ref를 통해 메서드 노출
export function start() {
  instanceRef?.start();
}

export function stop() {
  instanceRef?.stop();
}

export function reset() {
  instanceRef?.reset();
}

export function setText(newText: string) {
  instanceRef?.setText(newText);
}

export function destroy() {
  if (instanceRef) {
    instanceRef.destroy();
    instanceRef = null;
  }
}
</script>

<div bind:this={containerRef} class={className} style={style}></div>

// src/react/typing/Typing.tsx
import React, { useEffect, useRef } from 'react';
import { Typing } from '../../core/typing/index.js';
import type { TypingOptions } from '../../core/typing/index.js';

export interface TypingRef {
  start: () => void;
  stop: () => void;
  reset: () => void;
  setText: (text: string) => void;
  destroy: () => void;
}

interface TypingProps extends Omit<TypingOptions, 'onUpdate' | 'onComplete'> {
  className?: string;
  style?: React.CSSProperties;
  onUpdate?: (text: string) => void;
  onComplete?: () => void;
}

const TypingComponent = React.forwardRef<TypingRef, TypingProps>((props, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<Typing | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    // 이미 인스턴스가 있으면 생성하지 않음 (React Strict Mode 대응)
    if (instanceRef.current) {
      return;
    }

    const {
      text,
      speed,
      delay,
      enabled,
      threshold,
      rootMargin,
      triggerOnce,
      showCursor,
      cursorChar,
      onUpdate,
      onComplete,
    } = props;

    const options: TypingOptions = {
      text,
      speed,
      delay,
      enabled,
      threshold,
      rootMargin,
      triggerOnce,
      showCursor,
      cursorChar,
      onUpdate,
      onComplete,
    };

    instanceRef.current = new Typing(containerRef.current, options);

    return () => {
      if (instanceRef.current) {
        instanceRef.current.destroy();
        instanceRef.current = null;
      }
    };
  }, []);

  // props 변경 시 설정 업데이트
  useEffect(() => {
    if (!instanceRef.current) return;

    const { text } = props;

    // text가 변경되면 setText 호출
    if (text !== undefined && text !== instanceRef.current['originalText']) {
      instanceRef.current.setText(text);
    }
  }, [props.text]);

  React.useImperativeHandle(ref, () => ({
    start: () => {
      if (!instanceRef.current) {
        console.warn('Typing: 인스턴스가 아직 초기화되지 않았습니다.');
        return;
      }
      instanceRef.current.start();
    },
    stop: () => {
      if (!instanceRef.current) {
        console.warn('Typing: 인스턴스가 아직 초기화되지 않았습니다.');
        return;
      }
      instanceRef.current.stop();
    },
    reset: () => {
      if (!instanceRef.current) {
        console.warn('Typing: 인스턴스가 아직 초기화되지 않았습니다.');
        return;
      }
      instanceRef.current.reset();
    },
    setText: (text: string) => {
      if (!instanceRef.current) {
        console.warn('Typing: 인스턴스가 아직 초기화되지 않았습니다.');
        return;
      }
      instanceRef.current.setText(text);
    },
    destroy: () => {
      if (instanceRef.current) {
        instanceRef.current.destroy();
        instanceRef.current = null;
      }
    },
  }));

  return <div ref={containerRef} className={props.className} style={props.style} />;
});

TypingComponent.displayName = 'Typing';

export default TypingComponent;
